first_number = int(input("Enter the first number: "))
second_number = float(input("Enter the second number: "))
print(f"Sum = {first_number + second_number}")
print(f"Product = {first_number * second_number}")
print(f"Difference = {first_number - second_number}")
print(f"Division = {round(first_number / second_number)}")
print(f"Remainder = {round(first_number % second_number)}")
a = input("Enter a value: ")
print(type(a))
print(bool(a))